### ISSUE TITLE
Support vinyl-fs?

### ISSUE THREAD

**Issue by VigneshPeriasami** [jchip/xclap#1]
Gulp being the most used build tool and having a large set of already available plugins, mostly I see gulp extensions they depend on vinyl-fs stream pattern. If xclap could provide an extension so that the gulp users can easily migrate their gulp tasks to xclap with same streaming pattern will be very useful.

I understand that this is achievable by directly importing `vinyl-fs` in xclap build file, was wondering if xclap has a different plan in achieving the similar goal.

```javascript
// similar to gulp
xclap.src(["./src/**/*.js"]).pipe(babel(opts)).pipe(xclap.dest("./dest"));
```

**Comment by jchip** [comment]
thanks for the idea, but such feature is not the goal of this module.

this module aims to be a feature rich npm scripts compatible JS tasks executor.

If you want to use this task executor with gulp, that's perfectly possible.  You just write your tasks in JS that's in the task format this module requires, and directly use gulp in your function.

The only thing is, handling stream returned from your tasks is not implemented.

**Comment by VigneshPeriasami** [comment]
Got it, so clap is like a build task organizer rather than providing utilities to construct a task.

**Comment by jchip** [comment]
yeah, depends on what you mean with `task organizer`.  It's a task orchestrator and executor.  gulp actually comes with one too, except it lacks a few features xclap has.

**Comment by VigneshPeriasami** [comment]
thanks @jchip orchestrator makes more sense and reasons why it can't give utilities to create task.
