### ISSUE TITLE
jest's interactive --watch doesn't work

### ISSUE THREAD

**Issue by Anujan** [jchip/xclap#13]
Jest's interactive `--watch` mode doesn't work when run with clap

**To Reproduce:** 
Create clap task that runs `jest --watch`.

**Expected:** Watch mode gives you interactive menu to continue with
**Outcome:** watch mode just stalls after running tests

**Comment by jchip** [comment]
Fixed by 0.2.24.

```js
{
  foo: "~(tty)$jest --watch"
}
```

Note the above still run in concurrent mode so another task that also try to take tty could run.

To force everything else to stop and wait:

```js
{
  foo: "~(tty,sync)$jest --watch"
}
```
