### ISSUE TITLE
Doc and code inconsistency

### ISSUE THREAD

**Issue by bodawei** [jchip/xclap#5]
This page of doc: https://github.com/jchip/xclap/blob/HEAD/REFERENCE.md says

```
Then function can return:

-   `string` - `clap` will treat the string as a shell command to be spawned.
```

But the actual code appears to treat a single string return as a target to invoke.  See the text in `xclap.spec.js` named `should exe task name return by function`.

I'm not sure which is correct.  Personally, the doc seems the more uniform behavior, since if I want a task executed, I merely need to say `return  [ 'taskname' ];`

**Comment by jchip** [comment]
thanks, docs updated.
