### ISSUE TITLE
Provide example to retrieve task options

### ISSUE THREAD

**Issue by mspoerer** [jchip/xclap#6]
The ReadMe mentions the possibility to specify task options. Please provide an example or test of how to access those options.

**Comment by jchip** [comment]
https://github.com/jchip/xclap/blob/master/REFERENCE.md#task-options

**Comment by jchip** [comment]
also, you can use https://www.npmjs.com/package/nix-clap to parse the argv

**Comment by mspoerer** [comment]
thx. I somehow missed this part of the documentation.
