### ISSUE TITLE
argv is at 'this.process.argv' not 'this.argv'

### ISSUE THREAD

**Issue by soundyogi** [jchip/xclap#9]
Title says it.
this.argv is undefined for me.

https://github.com/jchip/xclap/blob/master/REFERENCE.md#task-options

We use xclap-cli is that the reason?
Thanks!

**Comment by jchip** [comment]
you are probably using fat arrow function for your task.  `this` for fat arrow functions behave differently than normal `function`.

**Comment by soundyogi** [comment]
Of Course!
Becuse they dont have 'this' and it points to the parent context!

Im stupid!

Thanks!
